add_executable(ns_cli ns_cli.c)
add_executable(ns_dlread ns_dlread.c)
add_executable(ns_nspprint ns_nspprint.c)
add_executable(ns_nsspprint ns_nsspprint.c)
add_executable(ns_walpprint ns_walpprint.c)
add_executable(print_all_vars print_all_vars.c)
add_executable(print_query print_query.c)
add_executable(print_type print_type.c)
add_executable(resolve_type_ref resolve_type_ref.c)
add_executable(ns_simtest ns_simtest.c)

target_link_libraries(ns_cli PRIVATE numstore.library.private)
target_link_libraries(ns_dlread PRIVATE numstore.library.private)
target_link_libraries(ns_nspprint PRIVATE numstore.library.private)
target_link_libraries(ns_nsspprint PRIVATE numstore.library.private)
target_link_libraries(ns_walpprint PRIVATE numstore.library.private)
target_link_libraries(print_all_vars PRIVATE numstore.library.private)
target_link_libraries(print_query PRIVATE numstore.library.private)
target_link_libraries(print_type PRIVATE numstore.library.private)
target_link_libraries(resolve_type_ref PRIVATE numstore.library.private)
target_link_libraries(ns_simtest PRIVATE numstore.library.private)

add_subdirectory(samples)
add_subdirectory(unit_tests)
