from __future__ import annotations

from typing import Any, overload

import numpy as np
import numpy.typing as npt

def ns_to_np(s: str) -> np.dtype:
    ...

def db_open(path: str) -> Any:
    ...

def db_close(db: Any) -> None:
    ...

def db_begin(db: Any) -> Any:
    ...

def txn_commit(txn: Any) -> None:
    ...

def txn_rollback(txn: Any) -> None:
    ...

def var_create(db: Any, txn: Any, var: str, dtype: str | np.dtype) -> None:
    ...

def var_newvar(db: Any, txn: Any, var: str, data: npt.NDArray) -> None:
    ...

def var_delete(db: Any, txn: Any, var: str) -> None:
    ...

def var_len(db: Any, txn: Any, var: str) -> int:
    ...

@overload
def var_read(db: Any, txn: Any, var: str, key: int)   -> Any: ...

@overload
def var_read(db: Any, txn: Any, var: str, key: range) -> npt.NDArray: ...

def var_read(db: Any, txn: Any, var: str, key: int | range) -> Any | npt.NDArray:
    ...

def var_insert(db: Any, txn: Any, var: str, ofst: int, data: npt.NDArray) -> None:
    ...

@overload
def var_write(db: Any, txn: Any, var: str, key: int,   data: Any)     -> None: ...

@overload
def var_write(db: Any, txn: Any, var: str, key: range, data: npt.NDArray) -> None: ...

def var_write(db: Any, txn: Any, var: str, key: int | range, data: Any | npt.NDArray) -> None:
    ...

@overload
def var_remove(db: Any, txn: Any, var: str, key: int)   -> Any: ...

@overload
def var_remove(db: Any, txn: Any, var: str, key: range) -> npt.NDArray: ...

def var_remove(db: Any, txn: Any, var: str, key: int | range) -> Any | npt.NDArray:
    ...
