// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_open
SEXP cpp_open(std::string path);
RcppExport SEXP _numstore_cpp_open(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_open(path));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smfile_open
SEXP cpp_smfile_open(std::string path);
RcppExport SEXP _numstore_cpp_smfile_open(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smfile_open(path));
    return rcpp_result_gen;
END_RCPP
}
// cpp_close
void cpp_close(SEXP h);
RcppExport SEXP _numstore_cpp_close(SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    cpp_close(h);
    return R_NilValue;
END_RCPP
}
// cpp_crash
void cpp_crash(SEXP h);
RcppExport SEXP _numstore_cpp_crash(SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    cpp_crash(h);
    return R_NilValue;
END_RCPP
}
// cpp_is_open
bool cpp_is_open(SEXP h);
RcppExport SEXP _numstore_cpp_is_open(SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_is_open(h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cleanup
void cpp_cleanup(std::string path);
RcppExport SEXP _numstore_cpp_cleanup(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    cpp_cleanup(path);
    return R_NilValue;
END_RCPP
}
// cpp_last_error
std::string cpp_last_error(SEXP h);
RcppExport SEXP _numstore_cpp_last_error(SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_last_error(h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_begin
SEXP cpp_begin(SEXP h);
RcppExport SEXP _numstore_cpp_begin(SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_begin(h));
    return rcpp_result_gen;
END_RCPP
}
// cpp_commit
void cpp_commit(SEXP x);
RcppExport SEXP _numstore_cpp_commit(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    cpp_commit(x);
    return R_NilValue;
END_RCPP
}
// cpp_rollback
void cpp_rollback(SEXP x);
RcppExport SEXP _numstore_cpp_rollback(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    cpp_rollback(x);
    return R_NilValue;
END_RCPP
}
// cpp_txn_active
bool cpp_txn_active(SEXP x);
RcppExport SEXP _numstore_cpp_txn_active(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_txn_active(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_execute
void cpp_execute(SEXP x, std::string query);
RcppExport SEXP _numstore_cpp_execute(SEXP xSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    cpp_execute(x, query);
    return R_NilValue;
END_RCPP
}
// cpp_var_len
double cpp_var_len(SEXP x, std::string query);
RcppExport SEXP _numstore_cpp_var_len(SEXP xSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_var_len(x, query));
    return rcpp_result_gen;
END_RCPP
}
// cpp_read
SEXP cpp_read(SEXP x, std::string query, std::string type);
RcppExport SEXP _numstore_cpp_read(SEXP xSEXP, SEXP querySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_read(x, query, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_write
double cpp_write(SEXP x, std::string query, SEXP values, std::string type);
RcppExport SEXP _numstore_cpp_write(SEXP xSEXP, SEXP querySEXP, SEXP valuesSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_write(x, query, values, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plan
SEXP cpp_plan(SEXP h, std::string query);
RcppExport SEXP _numstore_cpp_plan(SEXP hSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type h(hSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_plan(h, query));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plan_execute
void cpp_plan_execute(SEXP p, SEXP x);
RcppExport SEXP _numstore_cpp_plan_execute(SEXP pSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    cpp_plan_execute(p, x);
    return R_NilValue;
END_RCPP
}
// cpp_plan_var_len
double cpp_plan_var_len(SEXP p, SEXP x);
RcppExport SEXP _numstore_cpp_plan_var_len(SEXP pSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_plan_var_len(p, x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plan_read
SEXP cpp_plan_read(SEXP p, SEXP x, std::string type);
RcppExport SEXP _numstore_cpp_plan_read(SEXP pSEXP, SEXP xSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_plan_read(p, x, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plan_write
double cpp_plan_write(SEXP p, SEXP x, SEXP values, std::string type);
RcppExport SEXP _numstore_cpp_plan_write(SEXP pSEXP, SEXP xSEXP, SEXP valuesSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_plan_write(p, x, values, type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plan_free
void cpp_plan_free(SEXP p);
RcppExport SEXP _numstore_cpp_plan_free(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type p(pSEXP);
    cpp_plan_free(p);
    return R_NilValue;
END_RCPP
}
// cpp_smf_size
double cpp_smf_size(SEXP x);
RcppExport SEXP _numstore_cpp_smf_size(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smf_size(x));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smf_insert
double cpp_smf_insert(SEXP x, SEXP values, std::string type, double offset);
RcppExport SEXP _numstore_cpp_smf_insert(SEXP xSEXP, SEXP valuesSEXP, SEXP typeSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smf_insert(x, values, type, offset));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smf_write
double cpp_smf_write(SEXP x, SEXP values, std::string type, double offset, double stride);
RcppExport SEXP _numstore_cpp_smf_write(SEXP xSEXP, SEXP valuesSEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP strideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type stride(strideSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smf_write(x, values, type, offset, stride));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smf_read
SEXP cpp_smf_read(SEXP x, double n, std::string type, double offset, double stride);
RcppExport SEXP _numstore_cpp_smf_read(SEXP xSEXP, SEXP nSEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP strideSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type stride(strideSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smf_read(x, n, type, offset, stride));
    return rcpp_result_gen;
END_RCPP
}
// cpp_smf_remove
SEXP cpp_smf_remove(SEXP x, double n, std::string type, double offset, double stride, bool keep);
RcppExport SEXP _numstore_cpp_smf_remove(SEXP xSEXP, SEXP nSEXP, SEXP typeSEXP, SEXP offsetSEXP, SEXP strideSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< double >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type stride(strideSEXP);
    Rcpp::traits::input_parameter< bool >::type keep(keepSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_smf_remove(x, n, type, offset, stride, keep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_numstore_cpp_open", (DL_FUNC) &_numstore_cpp_open, 1},
    {"_numstore_cpp_smfile_open", (DL_FUNC) &_numstore_cpp_smfile_open, 1},
    {"_numstore_cpp_close", (DL_FUNC) &_numstore_cpp_close, 1},
    {"_numstore_cpp_crash", (DL_FUNC) &_numstore_cpp_crash, 1},
    {"_numstore_cpp_is_open", (DL_FUNC) &_numstore_cpp_is_open, 1},
    {"_numstore_cpp_cleanup", (DL_FUNC) &_numstore_cpp_cleanup, 1},
    {"_numstore_cpp_last_error", (DL_FUNC) &_numstore_cpp_last_error, 1},
    {"_numstore_cpp_begin", (DL_FUNC) &_numstore_cpp_begin, 1},
    {"_numstore_cpp_commit", (DL_FUNC) &_numstore_cpp_commit, 1},
    {"_numstore_cpp_rollback", (DL_FUNC) &_numstore_cpp_rollback, 1},
    {"_numstore_cpp_txn_active", (DL_FUNC) &_numstore_cpp_txn_active, 1},
    {"_numstore_cpp_execute", (DL_FUNC) &_numstore_cpp_execute, 2},
    {"_numstore_cpp_var_len", (DL_FUNC) &_numstore_cpp_var_len, 2},
    {"_numstore_cpp_read", (DL_FUNC) &_numstore_cpp_read, 3},
    {"_numstore_cpp_write", (DL_FUNC) &_numstore_cpp_write, 4},
    {"_numstore_cpp_plan", (DL_FUNC) &_numstore_cpp_plan, 2},
    {"_numstore_cpp_plan_execute", (DL_FUNC) &_numstore_cpp_plan_execute, 2},
    {"_numstore_cpp_plan_var_len", (DL_FUNC) &_numstore_cpp_plan_var_len, 2},
    {"_numstore_cpp_plan_read", (DL_FUNC) &_numstore_cpp_plan_read, 3},
    {"_numstore_cpp_plan_write", (DL_FUNC) &_numstore_cpp_plan_write, 4},
    {"_numstore_cpp_plan_free", (DL_FUNC) &_numstore_cpp_plan_free, 1},
    {"_numstore_cpp_smf_size", (DL_FUNC) &_numstore_cpp_smf_size, 1},
    {"_numstore_cpp_smf_insert", (DL_FUNC) &_numstore_cpp_smf_insert, 4},
    {"_numstore_cpp_smf_write", (DL_FUNC) &_numstore_cpp_smf_write, 5},
    {"_numstore_cpp_smf_read", (DL_FUNC) &_numstore_cpp_smf_read, 5},
    {"_numstore_cpp_smf_remove", (DL_FUNC) &_numstore_cpp_smf_remove, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_numstore(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
