from typing import Any
import numpy as np

# Utils
def ns_compile_type(s: str) -> np.dtype: ...

# Lifecycle
def db_open(path: str) -> Any: ...
def db_close(db: Any) -> None: ...

# Transactions
def db_begin(db: Any) -> Any: ...
def txn_commit(txn: Any) -> None: ...
def txn_rollback(txn: Any) -> None: ...

# Main Methods
def var_read(db: Any, txn_or_none: Any | None, var_id: int, key: Any) -> bytes: ...
def var_insert(db: Any, txn_or_none: Any | None, var_id: int, key: Any, data: Any) -> None: ...
def var_write(db: Any, txn_or_none: Any | None, var_id: int, key: Any, data: Any) -> None: ...
def var_len(db: Any, txn_or_none: Any | None, var_id: int) -> int: ...
def var_delete(db: Any, txn_or_none: Any | None, var_id: int, key: Any) -> None: ...
