import os
import re
import sys
from pathlib import Path

import numpy as np
from setuptools import Extension, setup

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent

# The C sources are listed in the per-module make fragments, which stay the
# single source of truth. Parsing them here (rather than reading a sources.txt
# generated by `make python-sources`) means a wheel build needs nothing but a
# C compiler: cibuildwheel runs `pip wheel` inside manylinux containers and on
# Windows under MSVC, where make is either absent or cannot drive this project.
# It also removes a stale-artifact failure mode - the generated sources.txt
# outlived a refactor and went on listing files that no longer existed.
MODULE_MKS = (
    "src/core/module.mk",
    "src/nscore/module.mk",
    "src/numstore/module.mk",
    "src/smartfiles/module.mk",
    "bindings/python/module.mk",
)

# `LIBNS_SRCS += path/to/file.c` / `ALL_PYSRCS += path/to/file.c`
SRC_LINE = re.compile(r"^\s*(?:LIBNS_SRCS|ALL_PYSRCS)\s*\+=\s*(\S+\.c)\s*$")


def read_sources() -> list[str]:
    sources: list[str] = []
    seen: set[str] = set()

    for mk in MODULE_MKS:
        mk_path = ROOT / mk
        if not mk_path.exists():
            sys.exit(f"error: {mk_path} not found; expected a numstore checkout")

        for line in mk_path.read_text().splitlines():
            match = SRC_LINE.match(line)
            if match is None:
                continue

            rel = match.group(1)
            src = ROOT / rel
            if not src.exists():
                sys.exit(f"error: {mk} lists {rel}, which does not exist")
            if rel in seen:
                continue

            seen.add(rel)
            # Relative to this setup.py, matching how setuptools lays out
            # build/temp object paths.
            sources.append(os.path.relpath(src, HERE))

    if not sources:
        sys.exit(f"error: no C sources found in {', '.join(MODULE_MKS)}")

    return sources


define_macros = [("NDEBUG", None), ("NLOG", None)]
extra_compile_args: list[str] = []
extra_link_args: list[str] = []
libraries: list[str] = []

if sys.platform == "win32":
    # The OS layer picks its Win32 implementation off _WIN32, so no extra
    # defines are needed - but MSVC compiles .c as C89 by default, and the
    # codebase is C11 (notably _Atomic / <stdatomic.h>, which MSVC only
    # exposes under this pair of flags).
    extra_compile_args += ["/std:c11", "/experimental:c11atomics"]
    # Keeps the CRT from rejecting the standard str*/fopen family.
    define_macros.append(("_CRT_SECURE_NO_WARNINGS", None))
else:
    # pthreads: on glibc older than 2.34 the pthread symbols live in a
    # separate library, so -pthread is needed at both compile and link time.
    # It is harmless (and still correct) on macOS and newer glibc, where they
    # are part of libc.
    extra_compile_args.append("-pthread")
    extra_link_args.append("-pthread")

if sys.platform.startswith("linux"):
    # long double / complex helpers land in libm on glibc.
    libraries.append("m")

ext = Extension(
    name="pynumstore._pynumstore",
    sources=read_sources(),
    include_dirs=[os.path.relpath(ROOT / "src", HERE), "./src/c", np.get_include()],
    define_macros=define_macros,
    extra_compile_args=extra_compile_args,
    extra_link_args=extra_link_args,
    libraries=libraries,
)

setup(
    name="pynumstore",
    packages=["pynumstore"],
    package_dir={"pynumstore": "src/pynumstore"},
    ext_modules=[ext],
    options={"build": {"build_base": os.environ.get("PYNUMSTORE_BUILD_BASE", "build")}},
)
