/// Copyright 2026 Theo Lincke
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///
///     http://www.apache.org/licenses/LICENSE-2.0
///
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.

/**
 * JNI glue between com.numstore.NativeLib and numstore.h.
 *
 * See NativeLib.java for the calling conventions. In short:
 *  - pointers are jlong (0 == NULL)
 *  - strings are NUL-terminated UTF-8 byte[]; queries are always passed to
 *    numstore as ("%s", query) so '%' is never interpreted
 *  - buffers are (Object buf, jint off, jint len) where buf is a byte[] or a
 *    direct ByteBuffer. Direct buffers are used in place. Arrays go through a
 *    malloc'd scratch copy instead of being pinned, because numstore calls may
 *    block on locks or I/O and GetPrimitiveArrayCritical must not be held
 *    across that.
 *  - failures throw com.numstore.NumstoreException with ns_strerror /
 *    ns_plan_strerror as the message.
 */

#include "numstore.h"

#include <jni.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// Generated by javac -h; including it makes the compiler check that every
// definition below matches its Java declaration.
#include "com_numstore_NativeLib.h"

// How numstore reports failure for int / sb_size returns.
// Centralised so it is a one-line change if the convention differs.
#define NS_FAILED(rc) ((rc) < 0)

#define DB(h)   ((nsdb_t *)(intptr_t)(h))
#define TXN(h)  ((txn_t *)(intptr_t)(h))
#define PLAN(h) ((nsdb_plan_t *)(intptr_t)(h))
#define VAR(h)  ((nsdb_var_t *)(intptr_t)(h))
#define PTR(p)  ((jlong)(intptr_t)(p))

//////////////////////////////////// Exceptions

static void
throw_class (JNIEnv *env, const char *cls, const char *msg)
{
  if ((*env)->ExceptionCheck (env)) {
    return; // keep the first exception
  }
  jclass c = (*env)->FindClass (env, cls);
  if (c != NULL) {
    (*env)->ThrowNew (env, c, msg);
    (*env)->DeleteLocalRef (env, c);
  }
}

static void
throw_ns (JNIEnv *env, const char *msg)
{
  throw_class (env, "com/numstore/NumstoreException", msg ? msg : "unknown numstore error");
}

// Throws using the error string of the plan if there is one, else the db.
static void
throw_last (JNIEnv *env, jlong db, jlong plan)
{
  const char *msg = NULL;
  if (plan != 0) {
    msg = ns_plan_strerror (PLAN (plan));
  } else if (db != 0) {
    msg = ns_strerror (DB (db));
  }
  throw_ns (env, msg);
}

//////////////////////////////////// Strings

typedef struct
{
  jbyteArray  arr;
  const char *str;
} cstr_t;

// Returns 0 on success. A NULL array yields str == NULL (used by plan calls).
static int
cstr_get (JNIEnv *env, jbyteArray arr, cstr_t *s)
{
  s->arr = arr;
  s->str = NULL;
  if (arr == NULL) {
    return 0;
  }
  s->str = (const char *)(*env)->GetByteArrayElements (env, arr, NULL);
  return s->str == NULL ? -1 : 0; // OutOfMemoryError already pending
}

static void
cstr_release (JNIEnv *env, cstr_t *s)
{
  if (s->str != NULL) {
    (*env)->ReleaseByteArrayElements (env, s->arr, (jbyte *)s->str, JNI_ABORT);
    s->str = NULL;
  }
}

//////////////////////////////////// Buffers

typedef struct
{
  jbyteArray arr; // non-NULL when ptr is a scratch copy of arr[off, off+len)
  jint       off;
  jint       len;
  void      *ptr;
} nbuf_t;

// Resolves (obj, off, len) to a native pointer. The scratch copy is always
// pre-filled from the array, so bytes numstore does not write keep their
// original values when copied back. Returns 0 on success.
static int
buf_get (JNIEnv *env, jobject obj, jint off, jint len, nbuf_t *b)
{
  memset (b, 0, sizeof *b);
  if (obj == NULL) {
    return 0;
  }

  void *addr = (*env)->GetDirectBufferAddress (env, obj);
  if (addr != NULL) {
    b->ptr = (char *)addr + off;
    b->len = len;
    return 0;
  }

  b->arr = (jbyteArray)obj;
  b->off = off;
  b->len = len;
  b->ptr = malloc (len > 0 ? (size_t)len : 1);
  if (b->ptr == NULL) {
    throw_class (env, "java/lang/OutOfMemoryError", "numstore_jni: scratch buffer");
    return -1;
  }
  if (len > 0) {
    (*env)->GetByteArrayRegion (env, b->arr, off, len, (jbyte *)b->ptr);
  }
  return 0;
}

// Frees the scratch copy, first copying it back into the array if requested.
static void
buf_release (JNIEnv *env, nbuf_t *b, int copy_back)
{
  if (b->arr != NULL) {
    if (copy_back && b->len > 0 && !(*env)->ExceptionCheck (env)) {
      (*env)->SetByteArrayRegion (env, b->arr, b->off, b->len, (const jbyte *)b->ptr);
    }
    free (b->ptr);
  }
  memset (b, 0, sizeof *b);
}

//////////////////////////////////// Lifecycle

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_open (JNIEnv *env, jclass cls, jbyteArray path)
{
  (void)cls;
  cstr_t p;
  if (cstr_get (env, path, &p)) {
    return 0;
  }
  nsdb_t *db = ns_open (p.str);
  cstr_release (env, &p);
  return PTR (db);
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_smfileOpen (JNIEnv *env, jclass cls, jbyteArray path)
{
  (void)cls;
  cstr_t p;
  if (cstr_get (env, path, &p)) {
    return 0;
  }
  nsdb_t *db = ns_smfile_open (p.str);
  cstr_release (env, &p);
  return PTR (db);
}

JNIEXPORT jint JNICALL
Java_com_numstore_NativeLib_cleanup (JNIEnv *env, jclass cls, jbyteArray path)
{
  (void)cls;
  cstr_t p;
  if (cstr_get (env, path, &p)) {
    return -1;
  }
  int rc = ns_cleanup (p.str);
  cstr_release (env, &p);
  return rc;
}

// The handle is gone after these, so no ns_strerror is available.
JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_close (JNIEnv *env, jclass cls, jlong db)
{
  (void)cls;
  if (NS_FAILED (ns_close (DB (db)))) {
    throw_ns (env, "ns_close failed");
  }
}

JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_crash (JNIEnv *env, jclass cls, jlong db)
{
  (void)cls;
  if (NS_FAILED (ns_crash (DB (db)))) {
    throw_ns (env, "ns_crash failed");
  }
}

//////////////////////////////////// Variables

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_varLen (JNIEnv *env, jclass cls, jlong var)
{
  (void)env;
  (void)cls;
  return (jlong)ns_var_len (VAR (var));
}

JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_varFree (JNIEnv *env, jclass cls, jlong var)
{
  (void)env;
  (void)cls;
  ns_var_free (VAR (var));
}

//////////////////////////////////// Transactions

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_begin (JNIEnv *env, jclass cls, jlong db)
{
  (void)cls;
  txn_t *tx = ns_begin (DB (db));
  if (tx == NULL) {
    throw_last (env, db, 0);
  }
  return PTR (tx);
}

JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_commit (JNIEnv *env, jclass cls, jlong db, jlong txn)
{
  (void)cls;
  if (NS_FAILED (ns_commit (DB (db), TXN (txn)))) {
    throw_last (env, db, 0);
  }
}

JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_rollback (JNIEnv *env, jclass cls, jlong db, jlong txn)
{
  (void)cls;
  if (NS_FAILED (ns_rollback (DB (db), TXN (txn)))) {
    throw_last (env, db, 0);
  }
}

//////////////////////////////////// Plans

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_planCreate (JNIEnv *env, jclass cls, jlong db, jbyteArray query)
{
  (void)cls;
  cstr_t q;
  if (cstr_get (env, query, &q)) {
    return 0;
  }
  nsdb_plan_t *plan = ns_plan_fcreate (DB (db), "%s", q.str);
  cstr_release (env, &q);
  if (plan == NULL) {
    throw_last (env, db, 0);
  }
  return PTR (plan);
}

JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_planFree (JNIEnv *env, jclass cls, jlong plan)
{
  (void)env;
  (void)cls;
  ns_plan_free (PLAN (plan));
}

//////////////////////////////////// Queries (plan != 0 selects ns_plan_*)

JNIEXPORT void JNICALL
Java_com_numstore_NativeLib_execute (
    JNIEnv    *env,
    jclass     cls,
    jlong      db,
    jlong      plan,
    jlong      txn,
    jbyteArray query
)
{
  (void)cls;
  int rc;
  if (plan != 0) {
    rc = ns_plan_execute (PLAN (plan), TXN (txn));
  } else {
    cstr_t q;
    if (cstr_get (env, query, &q)) {
      return;
    }
    rc = ns_execute (DB (db), TXN (txn), "%s", q.str);
    cstr_release (env, &q);
  }
  if (NS_FAILED (rc)) {
    throw_last (env, db, plan);
  }
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_getVar (
    JNIEnv    *env,
    jclass     cls,
    jlong      db,
    jlong      plan,
    jlong      txn,
    jbyteArray query
)
{
  (void)cls;
  nsdb_var_t *var;
  if (plan != 0) {
    var = ns_plan_get_var (PLAN (plan), TXN (txn));
  } else {
    cstr_t q;
    if (cstr_get (env, query, &q)) {
      return 0;
    }
    var = ns_get_var (DB (db), TXN (txn), "%s", q.str);
    cstr_release (env, &q);
  }
  if (var == NULL) {
    throw_last (env, db, plan);
  }
  return PTR (var);
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_read (
    JNIEnv    *env,
    jclass     cls,
    jlong      db,
    jlong      plan,
    jlong      txn,
    jobject    buf,
    jint       off,
    jint       len,
    jbyteArray query
)
{
  (void)cls;
  nbuf_t  b;
  sb_size rc;
  if (buf_get (env, buf, off, len, &b)) {
    return -1;
  }
  if (plan != 0) {
    rc = ns_plan_read (PLAN (plan), TXN (txn), b.ptr, (b_size)len);
  } else {
    cstr_t q;
    if (cstr_get (env, query, &q)) {
      buf_release (env, &b, 0);
      return -1;
    }
    rc = ns_read (DB (db), TXN (txn), b.ptr, (b_size)len, "%s", q.str);
    cstr_release (env, &q);
  }
  buf_release (env, &b, !NS_FAILED (rc));
  if (NS_FAILED (rc)) {
    throw_last (env, db, plan);
  }
  return (jlong)rc;
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_write (
    JNIEnv    *env,
    jclass     cls,
    jlong      db,
    jlong      plan,
    jlong      txn,
    jobject    buf,
    jint       off,
    jint       len,
    jbyteArray query
)
{
  (void)cls;
  nbuf_t  b;
  sb_size rc;
  if (buf_get (env, buf, off, len, &b)) {
    return -1;
  }
  if (plan != 0) {
    rc = ns_plan_write (PLAN (plan), TXN (txn), b.ptr, (b_size)len);
  } else {
    cstr_t q;
    if (cstr_get (env, query, &q)) {
      buf_release (env, &b, 0);
      return -1;
    }
    rc = ns_write (DB (db), TXN (txn), b.ptr, (b_size)len, "%s", q.str);
    cstr_release (env, &q);
  }
  buf_release (env, &b, 0);
  if (NS_FAILED (rc)) {
    throw_last (env, db, plan);
  }
  return (jlong)rc;
}

JNIEXPORT jbyteArray JNICALL
Java_com_numstore_NativeLib_mallocRead (
    JNIEnv    *env,
    jclass     cls,
    jlong      db,
    jlong      plan,
    jlong      txn,
    jbyteArray query
)
{
  (void)cls;
  b_size n = 0;
  void  *data;
  if (plan != 0) {
    data = ns_plan_malloc (PLAN (plan), TXN (txn), &n);
  } else {
    cstr_t q;
    if (cstr_get (env, query, &q)) {
      return NULL;
    }
    data = ns_malloc (DB (db), TXN (txn), &n, "%s", q.str);
    cstr_release (env, &q);
  }
  if (data == NULL) {
    throw_last (env, db, plan);
    return NULL;
  }
  if (n > (b_size)INT32_MAX) {
    free (data);
    throw_class (env, "java/lang/OutOfMemoryError", "numstore result is larger than a Java byte[]");
    return NULL;
  }
  jbyteArray out = (*env)->NewByteArray (env, (jsize)n);
  if (out != NULL && n > 0) {
    (*env)->SetByteArrayRegion (env, out, 0, (jsize)n, (const jbyte *)data);
  }
  free (data); // ns_malloc buffers are released with the system free()
  return out;
}

//////////////////////////////////// Smart files

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_smfSize (JNIEnv *env, jclass cls, jlong smf, jlong txn)
{
  (void)cls;
  sb_size rc = ns_smfile_size (DB (smf), TXN (txn));
  if (NS_FAILED (rc)) {
    throw_last (env, smf, 0);
  }
  return (jlong)rc;
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_smfInsert (
    JNIEnv *env,
    jclass  cls,
    jlong   smf,
    jlong   txn,
    jobject buf,
    jint    off,
    jint    len,
    jlong   bofst
)
{
  (void)cls;
  nbuf_t b;
  if (buf_get (env, buf, off, len, &b)) {
    return -1;
  }
  sb_size rc = ns_smfile_insert (DB (smf), TXN (txn), b.ptr, (sb_size)bofst, (b_size)len);
  buf_release (env, &b, 0);
  if (NS_FAILED (rc)) {
    throw_last (env, smf, 0);
  }
  return (jlong)rc;
}

// Buffer length for the strided calls; Java has already checked it fits.
#define STRIDED_LEN(size, nelem) ((jint)((jlong)(size) * (nelem)))

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_smfWrite (
    JNIEnv *env,
    jclass  cls,
    jlong   smf,
    jlong   txn,
    jobject buf,
    jint    off,
    jint    size,
    jlong   bofst,
    jlong   stride,
    jlong   nelem
)
{
  (void)cls;
  nbuf_t b;
  if (buf_get (env, buf, off, STRIDED_LEN (size, nelem), &b)) {
    return -1;
  }
  sb_size rc = ns_smfile_write (
      DB (smf),
      TXN (txn),
      b.ptr,
      (t_size)size,
      (sb_size)bofst,
      (sb_size)stride,
      (b_size)nelem
  );
  buf_release (env, &b, 0);
  if (NS_FAILED (rc)) {
    throw_last (env, smf, 0);
  }
  return (jlong)rc;
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_smfRead (
    JNIEnv *env,
    jclass  cls,
    jlong   smf,
    jlong   txn,
    jobject buf,
    jint    off,
    jint    size,
    jlong   bofst,
    jlong   stride,
    jlong   nelem
)
{
  (void)cls;
  nbuf_t b;
  if (buf_get (env, buf, off, STRIDED_LEN (size, nelem), &b)) {
    return -1;
  }
  sb_size rc = ns_smfile_read (
      DB (smf),
      TXN (txn),
      b.ptr,
      (t_size)size,
      (sb_size)bofst,
      (sb_size)stride,
      (b_size)nelem
  );
  buf_release (env, &b, !NS_FAILED (rc));
  if (NS_FAILED (rc)) {
    throw_last (env, smf, 0);
  }
  return (jlong)rc;
}

JNIEXPORT jlong JNICALL
Java_com_numstore_NativeLib_smfRemove (
    JNIEnv *env,
    jclass  cls,
    jlong   smf,
    jlong   txn,
    jobject buf,
    jint    off,
    jint    size,
    jlong   bofst,
    jlong   stride,
    jlong   nelem
)
{
  (void)cls;
  nbuf_t b; // buf may be NULL: removed data is discarded
  if (buf_get (env, buf, off, STRIDED_LEN (size, nelem), &b)) {
    return -1;
  }
  sb_size rc = ns_smfile_remove (
      DB (smf),
      TXN (txn),
      b.ptr,
      (t_size)size,
      (sb_size)bofst,
      (sb_size)stride,
      (b_size)nelem
  );
  buf_release (env, &b, !NS_FAILED (rc));
  if (NS_FAILED (rc)) {
    throw_last (env, smf, 0);
  }
  return (jlong)rc;
}
