# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_open <- function(path) {
    .Call(`_numstore_cpp_open`, path)
}

cpp_smfile_open <- function(path) {
    .Call(`_numstore_cpp_smfile_open`, path)
}

cpp_close <- function(h) {
    invisible(.Call(`_numstore_cpp_close`, h))
}

cpp_crash <- function(h) {
    invisible(.Call(`_numstore_cpp_crash`, h))
}

cpp_is_open <- function(h) {
    .Call(`_numstore_cpp_is_open`, h)
}

cpp_cleanup <- function(path) {
    invisible(.Call(`_numstore_cpp_cleanup`, path))
}

cpp_last_error <- function(h) {
    .Call(`_numstore_cpp_last_error`, h)
}

cpp_begin <- function(h) {
    .Call(`_numstore_cpp_begin`, h)
}

cpp_commit <- function(x) {
    invisible(.Call(`_numstore_cpp_commit`, x))
}

cpp_rollback <- function(x) {
    invisible(.Call(`_numstore_cpp_rollback`, x))
}

cpp_txn_active <- function(x) {
    .Call(`_numstore_cpp_txn_active`, x)
}

cpp_execute <- function(x, query) {
    invisible(.Call(`_numstore_cpp_execute`, x, query))
}

cpp_var_len <- function(x, query) {
    .Call(`_numstore_cpp_var_len`, x, query)
}

cpp_read <- function(x, query, type) {
    .Call(`_numstore_cpp_read`, x, query, type)
}

cpp_write <- function(x, query, values, type) {
    .Call(`_numstore_cpp_write`, x, query, values, type)
}

cpp_plan <- function(h, query) {
    .Call(`_numstore_cpp_plan`, h, query)
}

cpp_plan_execute <- function(p, x) {
    invisible(.Call(`_numstore_cpp_plan_execute`, p, x))
}

cpp_plan_var_len <- function(p, x) {
    .Call(`_numstore_cpp_plan_var_len`, p, x)
}

cpp_plan_read <- function(p, x, type) {
    .Call(`_numstore_cpp_plan_read`, p, x, type)
}

cpp_plan_write <- function(p, x, values, type) {
    .Call(`_numstore_cpp_plan_write`, p, x, values, type)
}

cpp_plan_free <- function(p) {
    invisible(.Call(`_numstore_cpp_plan_free`, p))
}

cpp_smf_size <- function(x) {
    .Call(`_numstore_cpp_smf_size`, x)
}

cpp_smf_insert <- function(x, values, type, offset) {
    .Call(`_numstore_cpp_smf_insert`, x, values, type, offset)
}

cpp_smf_write <- function(x, values, type, offset, stride) {
    .Call(`_numstore_cpp_smf_write`, x, values, type, offset, stride)
}

cpp_smf_read <- function(x, n, type, offset, stride) {
    .Call(`_numstore_cpp_smf_read`, x, n, type, offset, stride)
}

cpp_smf_remove <- function(x, n, type, offset, stride, keep) {
    .Call(`_numstore_cpp_smf_remove`, x, n, type, offset, stride, keep)
}

