name: Build And Test (Qemu)
on:
  workflow_call:
    inputs:
      builds:
        description: >
          JSON array of build definitions, each with dockcross and qemu.
          e.g. [{"dockcross":"linux-arm64","qemu":"aarch64"},
                {"dockcross":"linux-armv7","qemu":"arm"}]
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(inputs.builds) }}
    name: ${{ matrix.dockcross }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.qemu }}

      - name: Build Code with Dockcross
        run: |
          make clean
          make cross PLATFORM=${{ matrix.dockcross }} CROSS_GOAL="TARGET=debug"

      - name: Run Unit Tests Under QEMU
        run: |
          exe=./build/debug-${{ matrix.dockcross }}/target/bin/unit_tests
          dockcross_exe=./docker/dockcross-${{ matrix.dockcross }}
          $dockcross_exe $exe

      - name: Run Swarm Tests Under QEMU
        run: |
          dbname=swarm_test_${{ matrix.dockcross }}.db
          duration=10
          seed=$(shuf -i 10-500000000 -n 1)
          commit_hash=${{ github.sha }}
          seq_id=$(shuf -i 10-500000000 -n 1)
          exe=./build/debug-${{ matrix.dockcross }}/target/bin/numstore_simulation_test
          dockcross_exe=./docker/dockcross-${{ matrix.dockcross }}
          $dockcross_exe $exe $dbname $duration $seed $commit_hash $seq_id

      - name: Build release targets
        run: |
          make cross PLATFORM=${{ matrix.dockcross }} CROSS_GOAL="TARGET=release"
          cp ./docs/release_docs.md build/release-${{ matrix.dockcross }}/target/README.md 

      - name: Compress and upload
        uses: ./.github/actions/compress-and-upload
        with:
          folder: ./build/release-${{ matrix.dockcross }}/target
          artifact-name: release-${{ matrix.dockcross }}
