name: Build And Test
on:
  workflow_call:
    inputs:
      platforms:
        description: >
          JSON array of platforms, e.g. ["ubuntu-latest", "windows-latest"]
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Build Code
        run: |
          make clean
          make TARGET=debug NLOG=1

      - name: Run Unit Tests
        run: |
          seed=$(shuf -i 10-500000000 -n 1)
          exe=$(find build/debug -type f -maxdepth 3 -mindepth 3 -name unit_tests)
          $exe $seed

      # Disabled as swarm tests are in development
      # - name: Run swarm tests
      #   run: |
      #     dbname=swarm_test_${{ matrix.platform }}.db
      #     duration=10
      #     seed=$(shuf -i 10-500000000 -n 1)
      #     commit_hash=${{ github.sha }}
      #     seq_id=$(shuf -i 10-500000000 -n 1)
      #     exe=$(find build/debug -type f -name numstore_simulation_test)
      #     $exe $dbname $duration $seed $commit_hash $seq_id

      - name: Build release package
        run: |
          make TARGET=release release-package
          pkg_dir=$(find build/release -mindepth 1 -maxdepth 1 -type d)
          echo "PKG_DIR=$pkg_dir" >> "$GITHUB_ENV"

      - name: Compress and upload
        uses: ./.github/actions/compress-and-upload
        with:
          folder: ${{ env.PKG_DIR }}
          artifact-name: release-${{ matrix.platform }}
