name: Build

on:
  workflow_call:
    inputs:
      platforms:
        description: 'JSON array of platforms, e.g. ["ubuntu-latest","dockcross-linux-arm64"]'
        required: false
        default: '["ubuntu-latest"]'
        type: string
      goal:
        description: 'JSON array of make goals, e.g. ["build","test"]'
        required: false
        default: '["all"]'
        type: string
      default_runner:
        description: 'Fallback GitHub runner to use for dockcross builds'
        required: false
        default: 'ubuntu-latest'
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.platforms) }}
        goal: ${{ fromJSON(inputs.goal) }}
    name: ${{ matrix.platform }} (${{ matrix.goal }})
    runs-on: |-
      ${{
        startsWith(matrix.platform, 'dockcross-') && inputs.default_runner || matrix.platform
      }}
    env:
      IS_DOCKCROSS: ${{ startsWith(matrix.platform, 'dockcross-') }}
    steps:
      - uses: actions/checkout@v4

      - name: Run on native hardware
        if: env.IS_DOCKCROSS == 'false'
        run: make ${{ matrix.goal }}

      - name: Run using dockcross
        if: env.IS_DOCKCROSS == 'true'
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          real_platform="${PLATFORM#dockcross-}"
          make cross PLATFORM="$real_platform" CROSS_GOAL="${{ matrix.goal }}"
