name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      platforms: '["ubuntu-latest","windows-latest","macos-latest","dockcross-android-x86_64"]'
      goal: '["example"]'
      default_runner: 'ubuntu-latest'
