name: CI (develop)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  tests:
    name: ci-tests / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - run: zig build test
