name: CI (develop)
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  # Run debug tests on the three main platforms
  tests:
    name: ci-tests / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      # Build + run all tests (debug profile)
      - run: cargo test --features unit_tests,irwr_tests,cgd_tests

  # Build and run release tests just once to ensure
  # no debug/release code broke the pipeline
  release-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --release --features unit_tests,irwr_tests,cgd_tests

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }

      - run: sudo apt-get install -y lcov

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Run coverage
        run: ./src/scripts/coverage.sh

      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.info
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
